// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(SigortaIslemleriContext))]
    partial class SigortaIslemleriContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Dask", b =>
                {
                    b.Property<int>("PolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolId"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Il")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prim")
                        .HasColumnType("float");

                    b.Property<string>("TanzimTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tc")
                        .HasColumnType("long");

                    b.Property<string>("VadeBaslangic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VadeBitis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolId");

                    b.ToTable("Dask");
                });

            modelBuilder.Entity("WebApplication1.Models.Kasko", b =>
                {
                    b.Property<int>("PolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolId"));

                    b.Property<string>("Aracmarka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aracmodel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prim")
                        .HasColumnType("float");

                    b.Property<string>("TanzimTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tc")
                        .HasColumnType("long");

                    b.Property<string>("VadeBaslangic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VadeBitis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolId");

                    b.ToTable("Kasko");
                });

            modelBuilder.Entity("WebApplication1.Models.PoliceModel", b =>
                {
                    b.Property<int>("PoliceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoliceId"));

                    b.Property<int>("KulId")
                        .HasColumnType("int");

                    b.Property<string>("PoliceDetay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoliceGrup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prim")
                        .HasColumnType("int");

                    b.Property<string>("SigortalananMulkiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SonTarih")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TanzimTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teminatlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VadeBaslangic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VadeBitis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PoliceId");

                    b.ToTable("Policeler");
                });

            modelBuilder.Entity("WebApplication1.Models.Saglik", b =>
                {
                    b.Property<int>("PolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prim")
                        .HasColumnType("float");

                    b.Property<string>("TanzimTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tc")
                        .HasColumnType("long");

                    b.Property<string>("VadeBaslangic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VadeBitis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sagliksigorta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolId");

                    b.ToTable("Saglik");
                });

            modelBuilder.Entity("WebApplication1.Models.SigortaIslemleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bilgiler");
                });

            modelBuilder.Entity("WebApplication1.Models.Trafik", b =>
                {
                    b.Property<int>("PolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlakaIlKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlakaKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prim")
                        .HasColumnType("float");

                    b.Property<string>("TanzimTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tc")
                        .HasColumnType("long");

                    b.Property<string>("VadeBaslangic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VadeBitis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolId");

                    b.ToTable("Trafik");
                });
#pragma warning restore 612, 618
        }
    }
}
